version: '3.8'
services:
  user:
    build: ./Backend/User
    ports:
      - "4001:5000"
    volumes:
      - ./Backend/User:/user
    # command: >  
    #   sh -c  "cd /user &&
    #           gunicorn -b 0.0.0.0:5000 user:app"

  service:
    build: ./Backend/Service
    ports:
      - "4002:5000"
    volumes:
      - ./Backend/Service:/service
    # command: >  
    #   sh -c  "cd /service &&
    #           gunicorn -b 0.0.0.0:5000 service:app"
    depends_on:
      - user